name: Run Reality Server
on:
  workflow_dispatch: # به شما اجازه می‌دهد سرور را دستی روشن کنید

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Xray Core
        run: |
          bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install
          
      - name: Configure VLESS Reality
          # در این بخش تنظیمات داکر و UUID شما اعمال می‌شود
        run: |
          mkdir -p /usr/local/etc/xray
          echo '{
            "log": { "loglevel": "warning" },
            "inbounds": [{
              "port": 443,
              "protocol": "vless",
              "settings": {
                "clients": [{ "id": "9f4e2468-b715-4c31-b3b3-85764b8d781a", "flow": "xtls-r-vision" }],
                "decryption": "none"
              },
              "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                  "show": true,
                  "dest": "www.docker.com:443",
                  "xver": 0,
                  "serverNames": ["www.docker.com"],
                  "privateKey": "یک_کلید_خصوصی_اینجا_تولید_میشود",
                  "shortIds": ["66"]
                }
              }
            }],
            "outbounds": [{ "protocol": "freedom" }]
          }' > /usr/local/etc/xray/config.json

      - name: Start Server & Create Tunnel
        run: |
          systemctl start xray
          # استفاده از یک تونلینگ فوری مثل tmate برای گرفتن آدرس سرور بدون نیاز به اکانت
          curl -L https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz | tar xJ
          ./tmate-2.4.0-static-linux-amd64/tmate -F
